### ISSUE TITLE
max_pages_rendered param > 1 for pdfs errors

### ISSUE THREAD

**Issue by ed4wg** [CybercentreCanada/assemblyline-service-document-preview#26]
I'm getting an error in the logs when a PDF is analyzed and the `max_pages_rendered` param is anything greater than 1. 

`(5l1Ktl88oQofjQdopCerXz/132e515a1b082af7a4dc9eedf8f9e45c4b701784844dc56dbc379eaa508dae35): '>' not supported between instances of 'str' and 'int'`

The service result comes back with 'empty results', but you see that error in the logs.

**Comment by cccs-rs** [comment]
Should be patched in: [v4.3.0.stable8](https://github.com/CybercentreCanada/assemblyline-service-document-preview/releases/tag/v4.3.0.stable8), [v4.3.1.dev2](https://github.com/CybercentreCanada/assemblyline-service-document-preview/releases/tag/v4.3.1.dev2)

**Comment by ed4wg** [comment]
working great - thanks!
